# Generated by Django 3.0.4 on 2020-04-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('in_hospital', models.TextField(blank=True, null=True)),
                ('recovered', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('serious', models.TextField()),
                ('death', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('tested_today', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
