# Generated by Django 3.0.4 on 2020-04-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='death',
            new_name='ICU_currently',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='recovered',
            new_name='dead_daily',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='in_hospital',
            new_name='hospital_currently',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='serious',
        ),
    ]
