# Generated by Django 3.0.4 on 2020-04-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_auto_20200413_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_currently',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000),
        ),
    ]
