# Generated by Django 3.0.4 on 2020-04-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_auto_20200413_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_increase',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_currently',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
