# Generated by Django 3.0.4 on 2020-04-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0004_auto_20200413_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='dead_daily',
            field=models.TextField(blank=True),
        ),
    ]
