# Generated by Django 3.0.4 on 2020-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0006_auto_20200413_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_currently',
            field=models.IntegerField(),
        ),
    ]
